replicaCount: 1

image:
  repository: "" 
  pullPolicy: IfNotPresent
  tag: ""  

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true 
  className: "traefik-dev" 
  annotations: {}
  hosts: []
  tls: []

env: {}

resources:
  requests:
    cpu: 50m 
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi       

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}